export const REQ = 'REQ'
export const SUCCESS = 'SUCCESS'
export const ERROR = 'ERROR'


export const SUCCESSMONTH = 'SUCCESSMONTH'

export const SUCCESSWEEK = 'SUCCESSWEEK'

export const SUCCESSEQUIMENT = 'SUCCESSEQUIMENT'


export const SUCCESSSERVICE = 'SUCCESSSERVICE'

export const SUCCESSSERVICEDETAIL = 'SUCCESSSERVICEDETAIL'



